export interface BookingFormData {
  dateOfBirth: Date | string | null;
  name: string | null;
  email: string | null;
  phone: string | null;
  contactMethod?: string;
  referralSource?: string;
  size: number | null;
  isColor: boolean;
  complexity?: number;
  selectedCategory: string | null;
  placementIndex: number;
  currentPlacement?: string | null;
  isCoverUp: boolean;
  pricing: {
    basePriceRaw: number;
    complexityPrice: number;
    placementPrice: number;
    colorPrice: number;
    coverUpPrice: number;
    total: number;
  };
  estimatedDurationMinutes?: number;
  estimatedSessions?: number;
  referenceImages: File[];
  creativeFreedom: number;
  specificRequirements: string | null;
  mustHaveElements: string | null;
  colorPreferences: string | null;
  placementNotes: string | null;
  appointmentDate: Date | null;
  appointmentTime: string | null;
  urgencyLevel?: string;
  artistPreference?: string;
  termsAgreed?: boolean;
  medicalConfirmed?: boolean;
  ageConfirmed?: boolean;
  instagramHandle?: string | null;
  facebookProfile?: string | null;
  preferredContactMethod?: string;
  primaryTattooStyle?: string | null;
  styleDescription?: string | null;
  placementSliderTouched: boolean;
  sizeSliderTouched: boolean;
  painLevel?: number;
  painReason?: string;
  visualComplexityScore?: number;
  carouselTouched?: boolean;
  firstTattoo: boolean | null;
  budgetRange: string | null;
  coverUpPhoto: string[];
  tattooDescription: string | null;
  sizeCategory: string | null;
  bodyRegion: string | null;
  bodyArea: string | null;
  additionalAreas: string | null;
  /** Whether client wants topical numbing cream for their session */
  numbingCream: boolean;
}
