import type { PageServerLoad } from './$types';

// Seed jobs — found today, April 13, 2026
const SEED_JOBS = [
	{
		id: 'seed-1',
		title: 'Founding Product Engineer',
		company: 'Bild AI',
		url: 'https://www.ycombinator.com/companies/bild-ai/jobs/dDMaxVN-founding-product-engineer',
		source: 'hackernews' as const,
		fit: 'strong' as const,
		payRange: null,
		location: 'YC W25',
		remote: 'Remote',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'Founding team AI company. Full-stack + AI integration experience directly maps.',
		fitSummary: 'Founding AI product, SvelteKit/React + AI APIs, end-to-end ownership',
		yourTags: 'AI Integration, SvelteKit, Founding Role, TypeScript',
		jdSnippet: 'Build AI products from scratch at YC W25 AI startup',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-2',
		title: 'Product Engineer — AI Agents for Growth',
		company: 'Lago',
		url: 'https://getlago.notion.site/Lago-Product-Engineer-AI-Agents-for-Growth-327ef63110d280cdb030ccf429d3e4d7',
		source: 'hackernews' as const,
		fit: 'strong' as const,
		payRange: null,
		location: 'YC S23',
		remote: 'Remote',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'Open-source billing platform. AI Agents focus. Node/SaaS background directly relevant.',
		fitSummary: 'SaaS billing platform, AI agents, Node.js, open-source',
		yourTags: 'SaaS, AI Agents, Node.js, Open Source, TypeScript',
		jdSnippet: 'Lead AI agent initiatives for growth at open-source billing startup',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-3',
		title: 'AI Agent Engineer',
		company: 'CollectWise',
		url: 'https://www.ycombinator.com/companies/collectwise/jobs/Ktc6m6o-ai-agent-engineer',
		source: 'hackernews' as const,
		fit: 'strong' as const,
		payRange: null,
		location: 'YC F24',
		remote: 'Remote',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'Your ArjoStyle AI chatbot work (Meta Graph API + AI consultation) maps directly here.',
		fitSummary: 'AI agents, chatbot/automation, LLM integration, YC startup',
		yourTags: 'AI Agents, Chatbots, LLMs, Automation, YC Startup',
		jdSnippet: 'Build AI agents for debt collection automation at YC F24',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-4',
		title: "Software Engineer — Build the World's Best AI Plan Checker",
		company: 'InspectMind AI',
		url: 'https://www.ycombinator.com/companies/inspectmind-ai/jobs/jQNra64-software-engineer-build-the-world-s-best-ai-plan-checker',
		source: 'hackernews' as const,
		fit: 'good' as const,
		payRange: null,
		location: 'YC W24',
		remote: 'Remote',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'AI evaluation/product. Generalist engineer — your full-stack breadth fits.',
		fitSummary: 'AI product engineering, full-stack, generalist',
		yourTags: 'AI, Full-Stack, Product Engineering, TypeScript',
		jdSnippet: 'Build AI plan checking/review product at YC W24',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-5',
		title: 'Agent Context Layer Engineer',
		company: 'Zep AI',
		url: 'https://www.ycombinator.com/companies/zep-ai/jobs',
		source: 'hackernews' as const,
		fit: 'good' as const,
		payRange: null,
		location: 'YC W24',
		remote: 'Remote',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'Memory/context layer for AI agents. Niche but growing area — your AI integration work relevant.',
		fitSummary: 'AI agent infrastructure, memory systems, LLM, Python/Node',
		yourTags: 'AI Agents, LLM Infrastructure, Memory Systems',
		jdSnippet: 'Build the context/memory layer powering AI agents at YC W24',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-6',
		title: 'Senior/Staff Software Engineer',
		company: 'Toma',
		url: 'https://www.ycombinator.com/companies/toma/jobs/2lrQI7S-sr-staff-software-engineer',
		source: 'hackernews' as const,
		fit: 'stretch' as const,
		payRange: null,
		location: 'YC W24',
		remote: 'Remote',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'AI automotive coworkers. Senior level — stretch but your shipping track record speaks.',
		fitSummary: 'Senior IC role, AI/robotics, strong track record needed',
		yourTags: 'AI, Senior IC, Full-Stack, Robotics',
		jdSnippet: 'Build AI automotive coworkers at YC W24 startup',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-7',
		title: 'Founding Engineering Lead',
		company: 'AnswerThis',
		url: 'https://www.ycombinator.com/companies/answerthis/jobs/CNdatw5-founding-engineering-lead',
		source: 'hackernews' as const,
		fit: 'strong' as const,
		payRange: null,
		location: 'YC F25',
		remote: 'Remote',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'Founding engineer at fresh YC startup. End-to-end ownership matches how you built Midcodes.',
		fitSummary: 'Founding engineer, full-stack, product ownership, YC F25',
		yourTags: 'Founding Engineer, Full-Stack, Product, YC, End-to-End Ownership',
		jdSnippet: 'Lead engineering at YC F25 startup — question-answering product',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-8',
		title: 'LLM Full-stack/Backend Developer',
		company: 'CloudDevs',
		url: 'https://weworkremotely.com/remote-jobs/clouddevs-full-stack-backend-developers-llm-focused',
		source: 'weworkremotely' as const,
		fit: 'strong' as const,
		payRange: '$50,000 - $74,999 USD',
		location: 'San Francisco',
		remote: 'Worldwide',
		jobType: 'Contract',
		status: 'new' as const,
		notes: 'Contract role (W-2). LLM focus. AI API integration work directly relevant. USD pay is great for PH market.',
		fitSummary: 'LLM integration, full-stack Node/SvelteKit, contract USD',
		yourTags: 'LLM, AI APIs, Node.js, SvelteKit, Contract, USD',
		jdSnippet: 'Build LLM-powered features for enterprise clients',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-9',
		title: 'Senior Software Engineer',
		company: 'WALTER',
		url: 'https://weworkremotely.com/remote-jobs/walter-senior-software-engineer',
		source: 'weworkremotely' as const,
		fit: 'good' as const,
		payRange: '$50,000 - $74,999 USD',
		location: null,
		remote: 'Remote',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'Remote-first fintech/healthtech. Senior level — diverse project range shows breadth.',
		fitSummary: 'Senior full-stack, fintech/healthtech, remote',
		yourTags: 'Senior, Full-Stack, Fintech, Healthtech',
		jdSnippet: 'Senior software engineer at remote-first company',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-10',
		title: 'Software Engineer',
		company: 'Sticker Mule',
		url: 'https://weworkremotely.com/remote-jobs/sticker-mule-software-engineer-2',
		source: 'weworkremotely' as const,
		fit: 'good' as const,
		payRange: '$100,000+ USD',
		location: 'New York, NY',
		remote: 'Worldwide',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'Top 100 company, $100K+ USD. Engineering culture brand. Solid full-stack fit.',
		fitSummary: 'Full-stack, product company, $100K+ USD, Top 100 company',
		yourTags: 'Full-Stack, Product Company, $100K+, USD',
		jdSnippet: "Build Sticker Mule's printing/infrastructure platform",
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-11',
		title: 'Full-Stack Engineering Lead',
		company: 'Rare Days',
		url: 'https://weworkremotely.com/remote-jobs/rare-days-full-stack-engineering-lead',
		source: 'weworkremotely' as const,
		fit: 'strong' as const,
		payRange: '$75,000 - $99,999 USD',
		location: 'Vancouver',
		remote: 'Worldwide',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'Engineering Lead — your 65+ project delivery track record and founding experience is exactly what they want.',
		fitSummary: 'Engineering lead, full-stack, $75-100K USD, founding/execution track record',
		yourTags: 'Engineering Lead, Full-Stack, $75-100K, Founding Experience, SaaS',
		jdSnippet: 'Lead full-stack engineering at Vancouver startup',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-12',
		title: 'Vibe Coder Wanted',
		company: 'Wonder Dog',
		url: 'https://weworkremotely.com/remote-jobs/wonder-dog-vibe-coder-wanted',
		source: 'weworkremotely' as const,
		fit: 'good' as const,
		payRange: '$100,000+ USD',
		location: 'Los Angeles, CA',
		remote: 'Worldwide',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: '"Vibe coder" = autonomous, shipping fast. Creative/meme culture. Unique framing.',
		fitSummary: 'Fast shipping, creative culture, full-stack, $100K+ USD',
		yourTags: 'Fast Shipping, Creative, Full-Stack, $100K+, USD',
		jdSnippet: 'Ship fast, think different, build cool stuff',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-13',
		title: 'Founding Platform Engineer',
		company: 'Converge',
		url: 'https://www.runconverge.com/careers/founding-platform-engineer',
		source: 'hackernews' as const,
		fit: 'strong' as const,
		payRange: null,
		location: 'NYC (Onsite)',
		remote: 'On-site',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'NYC onsite is a constraint but founding platform role is high-impact. Full-stack + systems thinking fits.',
		fitSummary: 'Founding platform engineer, systems architecture, NYC',
		yourTags: 'Founding Engineer, Platform, Systems, NYC',
		jdSnippet: 'Build platform infrastructure at Converge (YC S23)',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-14',
		title: 'Eng, GTM, and more — Automate BPOs',
		company: 'Kaizen',
		url: 'https://www.kaizenautomation.com/careers',
		source: 'hackernews' as const,
		fit: 'good' as const,
		payRange: null,
		location: 'YC P25',
		remote: 'Remote',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'BPO automation — your systems/POS/ERP work for PH businesses gives domain insight.',
		fitSummary: 'BPO automation, systems integration, Philippine market insight',
		yourTags: 'Automation, BPO, Systems, Philippines Market',
		jdSnippet: 'Automate BPOs at YC P25 startup',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-15',
		title: 'Database Internal Engineer (Rust)',
		company: 'ParadeDB',
		url: 'https://paradedb.notion.site/',
		source: 'hackernews' as const,
		fit: 'strong' as const,
		payRange: null,
		location: 'YC S23',
		remote: 'Remote',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'ParadeDB is a Postgres-compatible distributed database built in Rust. Direct Rust/Tauri v2 match — your systems-level thinking and Rust experience translate perfectly.',
		fitSummary: 'Direct Rust match, distributed databases, Postgres, YC S23',
		yourTags: 'Rust, Databases, Distributed Systems, Postgres, YC',
		jdSnippet: 'Build the internals of a Postgres-compatible distributed database in Rust',
		foundAt: new Date().toISOString()
	},
	{
		id: 'seed-16',
		title: 'Rust and DevRel Positions',
		company: 'Wasmer',
		url: 'https://www.workatastartup.com/companies/wasmer',
		source: 'hackernews' as const,
		fit: 'good' as const,
		payRange: null,
		location: 'YC S19',
		remote: 'Remote',
		jobType: 'Full-time',
		status: 'new' as const,
		notes: 'Wasmer is a WebAssembly runtime built in Rust. Rust match plus DevRel/playground content — your public-facing project demos (Tattoo Tide, Claw Agent) show similar energy.',
		fitSummary: 'Rust, WebAssembly, DevRel, YC S19',
		yourTags: 'Rust, WebAssembly, DevRel, Open Source',
		jdSnippet: 'Work on the WebAssembly runtime and developer relations at Wasmer (YC S19)',
		foundAt: new Date().toISOString()
	}
];

export const load: PageServerLoad = async () => {
	return {
		jobs: SEED_JOBS
	};
};
