// Auto-generated by scripts/generate-changelog.js — do not edit manually
import type { Release } from './changelog-types';

export const changelogData: Release[] = [
  {
    "version": "v0.1.12",
    "date": "2026-04-20",
    "commit": "224377a",
    "changes": [
      {
        "type": "misc",
        "label": "Misc",
        "color": "#a78bfa",
        "text": "chore(release): bump to v0.1.11"
      }
    ]
  },
  {
    "version": "v0.1.11",
    "date": "2026-04-18",
    "commit": "224377a",
    "changes": [
      {
        "type": "misc",
        "label": "Misc",
        "color": "#a78bfa",
        "text": "chore(release): bump to v0.1.10"
      }
    ]
  },
  {
    "version": "v0.1.10",
    "date": "2026-04-17",
    "commit": "224377a",
    "changes": [
      {
        "type": "misc",
        "label": "Misc",
        "color": "#a78bfa",
        "text": "chore(release): bump to v0.1.9"
      }
    ]
  },
  {
    "version": "v0.1.9",
    "date": "2026-04-16",
    "commit": "224377a",
    "changes": [
      {
        "type": "misc",
        "label": "Misc",
        "color": "#a78bfa",
        "text": "chore(release): bump to v0.1.8"
      }
    ]
  },
  {
    "version": "v0.1.8",
    "date": "2026-04-16",
    "commit": "224377a",
    "changes": [
      {
        "type": "fix",
        "label": "Fix",
        "color": "#f87171",
        "text": "fix(arjostyle-web): resolve type check errors"
      },
      {
        "type": "chore",
        "label": "Chore",
        "color": "#60a5fa",
        "text": "bump to v0.1.7 + regenerate changelog"
      },
      {
        "type": "misc",
        "label": "Misc",
        "color": "#a78bfa",
        "text": "chore(deps): add semver for version bump skill"
      }
    ]
  },
  {
    "version": "v0.1.7",
    "date": "2026-04-15",
    "commit": "224377a",
    "changes": [
      {
        "type": "fix",
        "label": "Fix",
        "color": "#f87171",
        "text": "fix(arjostyle-web): resolve type check errors"
      }
    ]
  },
  {
    "version": "v0.1.6",
    "date": "2026-04-14",
    "commit": "224377a",
    "changes": [
      {
        "type": "fix",
        "label": "Fix",
        "color": "#f87171",
        "text": "bake APP_VERSION into worker at build time via version.ts"
      },
      {
        "type": "fix",
        "label": "Fix",
        "color": "#f87171",
        "text": "use $VERSION shell var instead of ${{ env.VERSION }} in sed command"
      },
      {
        "type": "fix",
        "label": "Fix",
        "color": "#f87171",
        "text": "fetch full git history so git describe --tags finds all tags"
      }
    ]
  }
];
