// Auto-generated by scripts/generate-changelog.js — do not edit manually
import type { Release } from './changelog-types';

export const changelogData: Release[] = [
  {
    "version": "v0.1.6",
    "date": "2026-04-14",
    "commit": "a4b697c",
    "changes": [
      {
        "type": "fix",
        "label": "Fix",
        "color": "#f87171",
        "text": "bake APP_VERSION into worker at build time via version.ts"
      },
      {
        "type": "fix",
        "label": "Fix",
        "color": "#f87171",
        "text": "use $VERSION shell var instead of ${{ env.VERSION }} in sed command"
      },
      {
        "type": "fix",
        "label": "Fix",
        "color": "#f87171",
        "text": "fetch full git history so git describe --tags finds all tags"
      }
    ]
  }
];
